version: "3.8"

services:
 
# STREAMLIT
  data-streamlit:
    build:
      context: ./data-streamlit
    # depends_on:
    #   mysql-database:
    #     condition: service_healthy
    volumes:
      - ./data:/app/streamlit
    tty: true
    ports:
      # HTTP
      - target: 8501
        published: 8501
        protocol: tcp